contour_mode: max_only
label:
- color: '#ef2929'
  name: RongShu
- color: '#ef2929'
  name: base
- color: '#00ff00'
  name: '2'
- color: '#00ff00'
  name: '3'
- color: '#00ff00'
  name: '1'
- color: '#00ff00'
  name: Cat
language: zh
mask_alpha: 0.5
vertex_size: 2
